INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (1, 1, 'Alto Orinoco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (2, 1, 'Atabapo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (3, 1, 'Atures');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (4, 1, 'Autana');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (5, 1, 'Manapiare');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (6, 1, 'Maroa');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (7, 1, 'Río Negro');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (8, 2, 'Anaco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (9, 2, 'Aragua');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (10, 2, 'Manuel Ezequiel Bruzual');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (11, 2, 'Diego Bautista Urbaneja');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (12, 2, 'Fernando Peñalver');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (13, 2, 'Francisco Del Carmen Carvajal');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (14, 2, 'General Sir Arthur McGregor');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (15, 2, 'Guanta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (16, 2, 'Independencia');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (17, 2, 'José Gregorio Monagas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (18, 2, 'Juan Antonio Sotillo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (19, 2, 'Juan Manuel Cajigal');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (20, 2, 'Libertad');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (21, 2, 'Francisco de Miranda');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (22, 2, 'Pedro María Freites');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (23, 2, 'Píritu');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (24, 2, 'San José de Guanipa');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (25, 2, 'San Juan de Capistrano');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (26, 2, 'Santa Ana');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (27, 2, 'Simón Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (28, 2, 'Simón Rodríguez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (29, 3, 'Achaguas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (30, 3, 'Biruaca');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (31, 3, 'Muñóz');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (32, 3, 'Páez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (33, 3, 'Pedro Camejo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (34, 3, 'Rómulo Gallegos');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (35, 3, 'San Fernando');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (36, 4, 'Atanasio Girardot');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (37, 4, 'Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (38, 4, 'Camatagua');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (39, 4, 'Francisco Linares Alcántara');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (40, 4, 'José Ángel Lamas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (41, 4, 'José Félix Ribas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (42, 4, 'José Rafael Revenga');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (43, 4, 'Libertador');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (44, 4, 'Mario Briceño Iragorry');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (45, 4, 'Ocumare de la Costa de Oro');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (46, 4, 'San Casimiro');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (47, 4, 'San Sebastián');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (48, 4, 'Santiago Mariño');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (49, 4, 'Santos Michelena');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (50, 4, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (51, 4, 'Tovar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (52, 4, 'Urdaneta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (53, 4, 'Zamora');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (54, 5, 'Alberto Arvelo Torrealba');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (55, 5, 'Andrés Eloy Blanco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (56, 5, 'Antonio José de Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (57, 5, 'Arismendi');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (58, 5, 'Barinas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (59, 5, 'Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (60, 5, 'Cruz Paredes');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (61, 5, 'Ezequiel Zamora');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (62, 5, 'Obispos');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (63, 5, 'Pedraza');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (64, 5, 'Rojas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (65, 5, 'Sosa');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (66, 6, 'Caroní');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (67, 6, 'Cedeño');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (68, 6, 'El Callao');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (69, 6, 'Gran Sabana');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (70, 6, 'Heres');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (71, 6, 'Piar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (72, 6, 'Angostura (Raúl Leoni)');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (73, 6, 'Roscio');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (74, 6, 'Sifontes');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (75, 6, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (76, 6, 'Padre Pedro Chien');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (77, 7, 'Bejuma');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (78, 7, 'Carlos Arvelo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (79, 7, 'Diego Ibarra');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (80, 7, 'Guacara');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (81, 7, 'Juan José Mora');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (82, 7, 'Libertador');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (83, 7, 'Los Guayos');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (84, 7, 'Miranda');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (85, 7, 'Montalbán');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (86, 7, 'Naguanagua');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (87, 7, 'Puerto Cabello');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (88, 7, 'San Diego');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (89, 7, 'San Joaquín');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (90, 7, 'Valencia');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (91, 8, 'Anzoátegui');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (92, 8, 'Tinaquillo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (93, 8, 'Girardot');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (94, 8, 'Lima Blanco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (95, 8, 'Pao de San Juan Bautista');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (96, 8, 'Ricaurte');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (97, 8, 'Rómulo Gallegos');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (98, 8, 'San Carlos');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (99, 8, 'Tinaco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (100, 9, 'Antonio Díaz');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (101, 9, 'Casacoima');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (102, 9, 'Pedernales');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (103, 9, 'Tucupita');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (104, 10, 'Acosta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (105, 10, 'Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (106, 10, 'Buchivacoa');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (107, 10, 'Cacique Manaure');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (108, 10, 'Carirubana');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (109, 10, 'Colina');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (110, 10, 'Dabajuro');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (111, 10, 'Democracia');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (112, 10, 'Falcón');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (113, 10, 'Federación');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (114, 10, 'Jacura');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (115, 10, 'José Laurencio Silva');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (116, 10, 'Los Taques');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (117, 10, 'Mauroa');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (118, 10, 'Miranda');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (119, 10, 'Monseñor Iturriza');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (120, 10, 'Palmasola');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (121, 10, 'Petit');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (122, 10, 'Píritu');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (123, 10, 'San Francisco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (124, 10, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (125, 10, 'Tocópero');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (126, 10, 'Unión');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (127, 10, 'Urumaco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (128, 10, 'Zamora');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (129, 11, 'Camaguán');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (130, 11, 'Chaguaramas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (131, 11, 'El Socorro');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (132, 11, 'José Félix Ribas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (133, 11, 'José Tadeo Monagas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (134, 11, 'Juan Germán Roscio');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (135, 11, 'Julián Mellado');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (136, 11, 'Las Mercedes');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (137, 11, 'Leonardo Infante');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (138, 11, 'Pedro Zaraza');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (139, 11, 'Ortíz');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (140, 11, 'San Gerónimo de Guayabal');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (141, 11, 'San José de Guaribe');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (142, 11, 'Santa María de Ipire');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (143, 11, 'Sebastián Francisco de Miranda');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (144, 12, 'Andrés Eloy Blanco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (145, 12, 'Crespo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (146, 12, 'Iribarren');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (147, 12, 'Jiménez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (148, 12, 'Morán');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (149, 12, 'Palavecino');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (150, 12, 'Simón Planas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (151, 12, 'Torres');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (152, 12, 'Urdaneta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (179, 13, 'Alberto Adriani');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (180, 13, 'Andrés Bello');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (181, 13, 'Antonio Pinto Salinas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (182, 13, 'Aricagua');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (183, 13, 'Arzobispo Chacón');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (184, 13, 'Campo Elías');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (185, 13, 'Caracciolo Parra Olmedo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (186, 13, 'Cardenal Quintero');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (187, 13, 'Guaraque');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (188, 13, 'Julio César Salas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (189, 13, 'Justo Briceño');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (190, 13, 'Libertador');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (191, 13, 'Miranda');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (192, 13, 'Obispo Ramos de Lora');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (193, 13, 'Padre Noguera');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (194, 13, 'Pueblo Llano');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (195, 13, 'Rangel');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (196, 13, 'Rivas Dávila');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (197, 13, 'Santos Marquina');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (198, 13, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (199, 13, 'Tovar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (200, 13, 'Tulio Febres Cordero');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (201, 13, 'Zea');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (223, 14, 'Acevedo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (224, 14, 'Andrés Bello');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (225, 14, 'Baruta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (226, 14, 'Brión');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (227, 14, 'Buroz');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (228, 14, 'Carrizal');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (229, 14, 'Chacao');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (230, 14, 'Cristóbal Rojas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (231, 14, 'El Hatillo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (232, 14, 'Guaicaipuro');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (233, 14, 'Independencia');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (234, 14, 'Lander');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (235, 14, 'Los Salias');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (236, 14, 'Páez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (237, 14, 'Paz Castillo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (238, 14, 'Pedro Gual');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (239, 14, 'Plaza');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (240, 14, 'Simón Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (241, 14, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (242, 14, 'Urdaneta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (243, 14, 'Zamora');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (258, 15, 'Acosta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (259, 15, 'Aguasay');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (260, 15, 'Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (261, 15, 'Caripe');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (262, 15, 'Cedeño');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (263, 15, 'Ezequiel Zamora');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (264, 15, 'Libertador');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (265, 15, 'Maturín');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (266, 15, 'Piar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (267, 15, 'Punceres');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (268, 15, 'Santa Bárbara');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (269, 15, 'Sotillo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (270, 15, 'Uracoa');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (271, 16, 'Antolín del Campo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (272, 16, 'Arismendi');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (273, 16, 'García');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (274, 16, 'Gómez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (275, 16, 'Maneiro');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (276, 16, 'Marcano');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (277, 16, 'Mariño');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (278, 16, 'Península de Macanao');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (279, 16, 'Tubores');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (280, 16, 'Villalba');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (281, 16, 'Díaz');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (282, 17, 'Agua Blanca');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (283, 17, 'Araure');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (284, 17, 'Esteller');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (285, 17, 'Guanare');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (286, 17, 'Guanarito');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (287, 17, 'Monseñor José Vicente de Unda');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (288, 17, 'Ospino');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (289, 17, 'Páez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (290, 17, 'Papelón');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (291, 17, 'San Genaro de Boconoíto');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (292, 17, 'San Rafael de Onoto');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (293, 17, 'Santa Rosalía');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (294, 17, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (295, 17, 'Turén');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (296, 18, 'Andrés Eloy Blanco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (297, 18, 'Andrés Mata');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (298, 18, 'Arismendi');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (299, 18, 'Benítez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (300, 18, 'Bermúdez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (301, 18, 'Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (302, 18, 'Cajigal');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (303, 18, 'Cruz Salmerón Acosta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (304, 18, 'Libertador');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (305, 18, 'Mariño');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (306, 18, 'Mejía');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (307, 18, 'Montes');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (308, 18, 'Ribero');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (309, 18, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (310, 18, 'Valdéz');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (341, 19, 'Andrés Bello');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (342, 19, 'Antonio Rómulo Costa');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (343, 19, 'Ayacucho');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (344, 19, 'Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (345, 19, 'Cárdenas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (346, 19, 'Córdoba');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (347, 19, 'Fernández Feo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (348, 19, 'Francisco de Miranda');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (349, 19, 'García de Hevia');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (350, 19, 'Guásimos');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (351, 19, 'Independencia');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (352, 19, 'Jáuregui');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (353, 19, 'José María Vargas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (354, 19, 'Junín');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (355, 19, 'Libertad');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (356, 19, 'Libertador');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (357, 19, 'Lobatera');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (358, 19, 'Michelena');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (359, 19, 'Panamericano');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (360, 19, 'Pedro María Ureña');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (361, 19, 'Rafael Urdaneta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (362, 19, 'Samuel Darío Maldonado');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (363, 19, 'San Cristóbal');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (364, 19, 'Seboruco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (365, 19, 'Simón Rodríguez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (366, 19, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (367, 19, 'Torbes');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (368, 19, 'Uribante');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (369, 19, 'San Judas Tadeo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (370, 20, 'Andrés Bello');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (371, 20, 'Boconó');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (372, 20, 'Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (373, 20, 'Candelaria');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (374, 20, 'Carache');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (375, 20, 'Escuque');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (376, 20, 'José Felipe Márquez Cañizalez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (377, 20, 'Juan Vicente Campos Elías');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (378, 20, 'La Ceiba');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (379, 20, 'Miranda');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (380, 20, 'Monte Carmelo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (381, 20, 'Motatán');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (382, 20, 'Pampán');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (383, 20, 'Pampanito');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (384, 20, 'Rafael Rangel');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (385, 20, 'San Rafael de Carvajal');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (386, 20, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (387, 20, 'Trujillo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (388, 20, 'Urdaneta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (389, 20, 'Valera');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (390, 21, 'Vargas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (391, 22, 'Arístides Bastidas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (392, 22, 'Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (407, 22, 'Bruzual');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (408, 22, 'Cocorote');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (409, 22, 'Independencia');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (410, 22, 'José Antonio Páez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (411, 22, 'La Trinidad');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (412, 22, 'Manuel Monge');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (413, 22, 'Nirgua');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (414, 22, 'Peña');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (415, 22, 'San Felipe');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (416, 22, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (417, 22, 'Urachiche');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (418, 22, 'José Joaquín Veroes');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (441, 23, 'Almirante Padilla');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (442, 23, 'Baralt');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (443, 23, 'Cabimas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (444, 23, 'Catatumbo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (445, 23, 'Colón');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (446, 23, 'Francisco Javier Pulgar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (447, 23, 'Páez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (448, 23, 'Jesús Enrique Losada');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (449, 23, 'Jesús María Semprún');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (450, 23, 'La Cañada de Urdaneta');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (451, 23, 'Lagunillas');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (452, 23, 'Machiques de Perijá');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (453, 23, 'Mara');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (454, 23, 'Maracaibo');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (455, 23, 'Miranda');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (456, 23, 'Rosario de Perijá');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (457, 23, 'San Francisco');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (458, 23, 'Santa Rita');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (459, 23, 'Simón Bolívar');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (460, 23, 'Sucre');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (461, 23, 'Valmore Rodríguez');
INSERT INTO `municipios` (`id`, `entidad_id`, `nombre_municipio`)  VALUES (462, 24, 'Libertador');